name: VirtualPageResource\ProductShelf
behaviors:
  - ChangeTimeSavingBehavior
  - ShelfLoadBehavior

attributes:
  type: string !nullable Enum("ShelfTypeEnum")
  name: string !nullable
  code: string !nullable
  description: text

relations:
  products: (><) Product.productShelves
  virtualPages: (><) VirtualPage.productShelves

  category: (>-) ProductGroup\Category
  tag: (>-) ProductGroup\Tag
  promoTag: (>-) ProductGroup\PromoTag
