<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200906182152 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_type.audio_book (id SERIAL NOT NULL, product_id INT DEFAULT NULL, reader_id INT DEFAULT NULL, duration VARCHAR(255) DEFAULT NULL, rights_expiration TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9470E1E64584665A ON product_type.audio_book (product_id)');
        $this->addSql('CREATE INDEX IDX_9470E1E61717D737 ON product_type.audio_book (reader_id)');
        $this->addSql('CREATE TABLE common.audio_book_reader (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, en_name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, slug TEXT DEFAULT NULL, uri TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE common.author (id SERIAL NOT NULL, old_modx_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, en_name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, slug TEXT DEFAULT NULL, uri TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE util_rel.author__product_essence__essence (author_id INT NOT NULL, essence_id INT NOT NULL, PRIMARY KEY(author_id, essence_id))');
        $this->addSql('CREATE INDEX IDX_97964C37F675F31B ON util_rel.author__product_essence__essence (author_id)');
        $this->addSql('CREATE INDEX IDX_97964C379FAFD5C7 ON util_rel.author__product_essence__essence (essence_id)');
        $this->addSql('CREATE TABLE product_type.badge (id SERIAL NOT NULL, product_id INT DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3E54EA54584665A ON product_type.badge (product_id)');
        $this->addSql('CREATE TABLE product_type.bag (id SERIAL NOT NULL, product_id INT DEFAULT NULL, box VARCHAR(255) DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, depth INT DEFAULT NULL, handle_length INT DEFAULT NULL, handle_width INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_10623CE4584665A ON product_type.bag (product_id)');
        $this->addSql('CREATE TABLE virtual_page_resource.banner (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, link VARCHAR(255) NOT NULL, link_title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, frequency INT DEFAULT NULL, data_active_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, data_active_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active_mini_banner BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf (banner_id INT NOT NULL, banner_shelf_id INT NOT NULL, PRIMARY KEY(banner_id, banner_shelf_id))');
        $this->addSql('CREATE INDEX IDX_35B30188684EC833 ON util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf (banner_id)');
        $this->addSql('CREATE INDEX IDX_35B301887E2B35E3 ON util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf (banner_shelf_id)');
        $this->addSql('CREATE TABLE virtual_page_resource.banner_shelf (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE product_essence.book (id SERIAL NOT NULL, essence_id INT DEFAULT NULL, original_primary_name VARCHAR(2048) DEFAULT NULL, original_secondary_name VARCHAR(2048) DEFAULT NULL, quotes TEXT DEFAULT NULL, work_description TEXT DEFAULT NULL, posts TEXT DEFAULT NULL, team TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_999CA6CE9FAFD5C7 ON product_essence.book (essence_id)');
        $this->addSql('COMMENT ON COLUMN product_essence.book.quotes IS \'(DC2Type:dict)\'');
        $this->addSql('COMMENT ON COLUMN product_essence.book.posts IS \'(DC2Type:dict)\'');
        $this->addSql('COMMENT ON COLUMN product_essence.book.team IS \'(DC2Type:dict)\'');
        $this->addSql('CREATE TABLE product_type.bookmark (id SERIAL NOT NULL, product_id INT DEFAULT NULL, count INT DEFAULT NULL, box VARCHAR(255) DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AA87E854584665A ON product_type.bookmark (product_id)');
        $this->addSql('CREATE TABLE product_group.category (id SERIAL NOT NULL, parent_category_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BBCDFC04796A8F92 ON product_group.category (parent_category_id)');
        $this->addSql('CREATE TABLE product_type.certificate (id SERIAL NOT NULL, product_id INT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, parameters TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5BE6A4BC4584665A ON product_type.certificate (product_id)');
        $this->addSql('COMMENT ON COLUMN product_type.certificate.parameters IS \'(DC2Type:dict)\'');
        $this->addSql('CREATE TABLE product_type.cloth (id SERIAL NOT NULL, product_id INT DEFAULT NULL, box VARCHAR(255) DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, material_content VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FE46D064584665A ON product_type.cloth (product_id)');
        $this->addSql('CREATE TABLE product_property.color (id SERIAL NOT NULL, value VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE util_rel.product_property__color__product_type__cloth (color_id INT NOT NULL, cloth_id INT NOT NULL, PRIMARY KEY(color_id, cloth_id))');
        $this->addSql('CREATE INDEX IDX_5F922BEC7ADA1FB5 ON util_rel.product_property__color__product_type__cloth (color_id)');
        $this->addSql('CREATE INDEX IDX_5F922BECE53266EE ON util_rel.product_property__color__product_type__cloth (cloth_id)');
        $this->addSql('CREATE TABLE product_type.course (id SERIAL NOT NULL, product_id INT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, parameters TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D37941014584665A ON product_type.course (product_id)');
        $this->addSql('COMMENT ON COLUMN product_type.course.parameters IS \'(DC2Type:dict)\'');
        $this->addSql('CREATE TABLE common.creative_partner (id SERIAL NOT NULL, logo_id INT DEFAULT NULL, old_modx_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D2813ECFF98F144A ON common.creative_partner (logo_id)');
        $this->addSql('CREATE TABLE util_rel.creative_partner__product_essence__book (creative_partner_id INT NOT NULL, book_id INT NOT NULL, PRIMARY KEY(creative_partner_id, book_id))');
        $this->addSql('CREATE INDEX IDX_8B688F0151184328 ON util_rel.creative_partner__product_essence__book (creative_partner_id)');
        $this->addSql('CREATE INDEX IDX_8B688F0116A2B381 ON util_rel.creative_partner__product_essence__book (book_id)');
        $this->addSql('CREATE TABLE product_data.data1_c (id SERIAL NOT NULL, product_id INT DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, id1c VARCHAR(255) DEFAULT NULL, group1c VARCHAR(255) DEFAULT NULL, itf14 VARCHAR(255) DEFAULT NULL, vat VARCHAR(255) DEFAULT NULL, quantity_per_pack INT DEFAULT NULL, rr_price INT DEFAULT NULL, weight INT DEFAULT NULL, height INT DEFAULT NULL, width INT DEFAULT NULL, length INT DEFAULT NULL, age_limit VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, is_defined BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EB91A6544584665A ON product_data.data1_c (product_id)');
        $this->addSql('CREATE TABLE product_type.e_book (id SERIAL NOT NULL, product_id INT DEFAULT NULL, rights_expiration TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7CFE35C54584665A ON product_type.e_book (product_id)');
        $this->addSql('CREATE TABLE product_essence.essence (id SERIAL NOT NULL, category_id INT DEFAULT NULL, series_id INT DEFAULT NULL, author_id INT DEFAULT NULL, full_name VARCHAR(255) NOT NULL, primary_name VARCHAR(255) NOT NULL, secondary_name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, full_description TEXT DEFAULT NULL, recommendations TEXT DEFAULT NULL, promo_stickers TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A0A91C8612469DE2 ON product_essence.essence (category_id)');
        $this->addSql('CREATE INDEX IDX_A0A91C865278319C ON product_essence.essence (series_id)');
        $this->addSql('CREATE INDEX IDX_A0A91C86F675F31B ON product_essence.essence (author_id)');
        $this->addSql('COMMENT ON COLUMN product_essence.essence.recommendations IS \'(DC2Type:dict)\'');
        $this->addSql('COMMENT ON COLUMN product_essence.essence.promo_stickers IS \'(DC2Type:dict)\'');
        $this->addSql('CREATE TABLE util_rel.product_essence__essence__essences_with_me__same_essences (essences_with_me_id INT NOT NULL, same_essences_id INT NOT NULL, PRIMARY KEY(essences_with_me_id, same_essences_id))');
        $this->addSql('CREATE INDEX IDX_9F1475F251FD9051 ON util_rel.product_essence__essence__essences_with_me__same_essences (essences_with_me_id)');
        $this->addSql('CREATE INDEX IDX_9F1475F2EAD75F8 ON util_rel.product_essence__essence__essences_with_me__same_essences (same_essences_id)');
        $this->addSql('CREATE TABLE util_rel.product_essence__essence__product_group__tag (essence_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(essence_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_A19F1F389FAFD5C7 ON util_rel.product_essence__essence__product_group__tag (essence_id)');
        $this->addSql('CREATE INDEX IDX_A19F1F38BAD26311 ON util_rel.product_essence__essence__product_group__tag (tag_id)');
        $this->addSql('CREATE TABLE virtual_page_resource.factoid (id SERIAL NOT NULL, image_id INT DEFAULT NULL, product_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D22BCE93DA5256D ON virtual_page_resource.factoid (image_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D22BCE94584665A ON virtual_page_resource.factoid (product_id)');
        $this->addSql('CREATE TABLE virtual_page_resource.free_block (id SERIAL NOT NULL, title VARCHAR(255) DEFAULT NULL, text TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE product_type.game (id SERIAL NOT NULL, product_id INT DEFAULT NULL, composition TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E368B764584665A ON product_type.game (product_id)');
        $this->addSql('CREATE TABLE product_type.kit (id SERIAL NOT NULL, product_id INT DEFAULT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42B0D3974584665A ON product_type.kit (product_id)');
        $this->addSql('COMMENT ON COLUMN product_type.kit.content IS \'(DC2Type:dict)\'');
        $this->addSql('CREATE TABLE product_type.kit_item (id SERIAL NOT NULL, product_id INT DEFAULT NULL, kit_id INT DEFAULT NULL, count INT DEFAULT NULL, name VARCHAR(2048) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_12E86BE54584665A ON product_type.kit_item (product_id)');
        $this->addSql('CREATE INDEX IDX_12E86BE53A8E60EF ON product_type.kit_item (kit_id)');
        $this->addSql('CREATE TABLE product_type.notepad (id SERIAL NOT NULL, product_id INT DEFAULT NULL, format_size VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_185A5F104584665A ON product_type.notepad (product_id)');
        $this->addSql('CREATE TABLE product_type.paper_book (id SERIAL NOT NULL, product_id INT DEFAULT NULL, price_labyrinth INT DEFAULT NULL, link_labyrinth VARCHAR(255) DEFAULT NULL, link_ozon VARCHAR(255) DEFAULT NULL, link_kniga_biz VARCHAR(255) DEFAULT NULL, rights_expiration TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D295CAD4584665A ON product_type.paper_book (product_id)');
        $this->addSql('CREATE TABLE product_type.postcard (id SERIAL NOT NULL, product_id INT DEFAULT NULL, count INT DEFAULT NULL, box VARCHAR(255) DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F2F2E0C24584665A ON product_type.postcard (product_id)');
        $this->addSql('CREATE TABLE product_type.poster (id SERIAL NOT NULL, product_id INT DEFAULT NULL, count INT DEFAULT NULL, format_size VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E896224A4584665A ON product_type.poster (product_id)');
        $this->addSql('CREATE TABLE common.product (id SERIAL NOT NULL, essence_id INT DEFAULT NULL, old_modx_id INT DEFAULT NULL, id_mif VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, price INT DEFAULT NULL, life_cycle_status INT NOT NULL, release_data TEXT DEFAULT NULL, start_sale_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planed_start_sale_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_dimensionless_for_present BOOLEAN NOT NULL, is_available_for_present BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_33AEC4FB9FAFD5C7 ON common.product (essence_id)');
        $this->addSql('CREATE TABLE util_rel.product__product_group__promo_tag (product_id INT NOT NULL, promo_tag_id INT NOT NULL, PRIMARY KEY(product_id, promo_tag_id))');
        $this->addSql('CREATE INDEX IDX_3158A30A4584665A ON util_rel.product__product_group__promo_tag (product_id)');
        $this->addSql('CREATE INDEX IDX_3158A30AA3577C5C ON util_rel.product__product_group__promo_tag (promo_tag_id)');
        $this->addSql('CREATE TABLE util_rel.product__virtual_page_resource__product_shelf (product_id INT NOT NULL, product_shelf_id INT NOT NULL, PRIMARY KEY(product_id, product_shelf_id))');
        $this->addSql('CREATE INDEX IDX_C5F984754584665A ON util_rel.product__virtual_page_resource__product_shelf (product_id)');
        $this->addSql('CREATE INDEX IDX_C5F98475B7A29157 ON util_rel.product__virtual_page_resource__product_shelf (product_shelf_id)');
        $this->addSql('CREATE TABLE util_rel.product__product_data__source (product_id INT NOT NULL, source_id INT NOT NULL, PRIMARY KEY(product_id, source_id))');
        $this->addSql('CREATE INDEX IDX_752918214584665A ON util_rel.product__product_data__source (product_id)');
        $this->addSql('CREATE INDEX IDX_75291821953C1C61 ON util_rel.product__product_data__source (source_id)');
        $this->addSql('CREATE TABLE virtual_page_resource.product_shelf (id SERIAL NOT NULL, category_id INT DEFAULT NULL, tag_id INT DEFAULT NULL, promo_tag_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1031995B12469DE2 ON virtual_page_resource.product_shelf (category_id)');
        $this->addSql('CREATE INDEX IDX_1031995BBAD26311 ON virtual_page_resource.product_shelf (tag_id)');
        $this->addSql('CREATE INDEX IDX_1031995BA3577C5C ON virtual_page_resource.product_shelf (promo_tag_id)');
        $this->addSql('CREATE TABLE product_data.promo_data (id SERIAL NOT NULL, product_id INT DEFAULT NULL, send_description TEXT DEFAULT NULL, passage_title VARCHAR(2048) DEFAULT NULL, passage_file VARCHAR(2048) DEFAULT NULL, meta_tag_description TEXT DEFAULT NULL, meta_tag_keywords TEXT DEFAULT NULL, meta_tag_og_image VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2578E2124584665A ON product_data.promo_data (product_id)');
        $this->addSql('CREATE TABLE product_group.promo_tag (id SERIAL NOT NULL, old_modx_id INT DEFAULT NULL, primary_name VARCHAR(255) DEFAULT NULL, secondary_name VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE product_group.series (id SERIAL NOT NULL, name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE product_property.size (id SERIAL NOT NULL, value_ru VARCHAR(255) DEFAULT NULL, value_eu VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE util_rel.product_property__size__product_type__cloth (size_id INT NOT NULL, cloth_id INT NOT NULL, PRIMARY KEY(size_id, cloth_id))');
        $this->addSql('CREATE INDEX IDX_8FFFBB80498DA827 ON util_rel.product_property__size__product_type__cloth (size_id)');
        $this->addSql('CREATE INDEX IDX_8FFFBB80E53266EE ON util_rel.product_property__size__product_type__cloth (cloth_id)');
        $this->addSql('CREATE TABLE auth.soc_network_user_data (id SERIAL NOT NULL, user_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, soc_network_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B7FB7888A76ED395 ON auth.soc_network_user_data (user_id)');
        $this->addSql('CREATE TABLE product_data.source (id SERIAL NOT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, value VARCHAR(2000) DEFAULT NULL, format VARCHAR(255) DEFAULT NULL, meta_data TEXT DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN product_data.source.meta_data IS \'(DC2Type:dict)\'');
        $this->addSql('CREATE TABLE util_rel.product_data__source__product_essence__essence (source_id INT NOT NULL, essence_id INT NOT NULL, PRIMARY KEY(source_id, essence_id))');
        $this->addSql('CREATE INDEX IDX_991923EE953C1C61 ON util_rel.product_data__source__product_essence__essence (source_id)');
        $this->addSql('CREATE INDEX IDX_991923EE9FAFD5C7 ON util_rel.product_data__source__product_essence__essence (essence_id)');
        $this->addSql('CREATE TABLE util_rel.product_data__source__virtual_page_resource__banner (source_id INT NOT NULL, banner_id INT NOT NULL, PRIMARY KEY(source_id, banner_id))');
        $this->addSql('CREATE INDEX IDX_7E0F8BBA953C1C61 ON util_rel.product_data__source__virtual_page_resource__banner (source_id)');
        $this->addSql('CREATE INDEX IDX_7E0F8BBA684EC833 ON util_rel.product_data__source__virtual_page_resource__banner (banner_id)');
        $this->addSql('CREATE TABLE product_type.sticker (id SERIAL NOT NULL, product_id INT DEFAULT NULL, count INT DEFAULT NULL, box VARCHAR(255) DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, diameter INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4A92606D4584665A ON product_type.sticker (product_id)');
        $this->addSql('CREATE TABLE product_group.tag (id SERIAL NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE common.virtual_page (id SERIAL NOT NULL, parent_virtual_page_id INT DEFAULT NULL, category_id INT DEFAULT NULL, icon_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug TEXT DEFAULT NULL, description TEXT DEFAULT NULL, level INT DEFAULT NULL, is_menu BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CC09F4E5ADFDB4D7 ON common.virtual_page (parent_virtual_page_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC09F4E512469DE2 ON common.virtual_page (category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC09F4E554B9D732 ON common.virtual_page (icon_id)');
        $this->addSql('CREATE TABLE util_rel.virtual_page__virtual_page_resource__banner_shelf (virtual_page_id INT NOT NULL, banner_shelf_id INT NOT NULL, PRIMARY KEY(virtual_page_id, banner_shelf_id))');
        $this->addSql('CREATE INDEX IDX_DE34ACB23A31B02B ON util_rel.virtual_page__virtual_page_resource__banner_shelf (virtual_page_id)');
        $this->addSql('CREATE INDEX IDX_DE34ACB27E2B35E3 ON util_rel.virtual_page__virtual_page_resource__banner_shelf (banner_shelf_id)');
        $this->addSql('CREATE TABLE util_rel.virtual_page__virtual_page_resource__product_shelf (virtual_page_id INT NOT NULL, product_shelf_id INT NOT NULL, PRIMARY KEY(virtual_page_id, product_shelf_id))');
        $this->addSql('CREATE INDEX IDX_9B72D8DC3A31B02B ON util_rel.virtual_page__virtual_page_resource__product_shelf (virtual_page_id)');
        $this->addSql('CREATE INDEX IDX_9B72D8DCB7A29157 ON util_rel.virtual_page__virtual_page_resource__product_shelf (product_shelf_id)');
        $this->addSql('CREATE TABLE util_rel.virtual_page__virtual_page_resource__banner (virtual_page_id INT NOT NULL, banner_id INT NOT NULL, PRIMARY KEY(virtual_page_id, banner_id))');
        $this->addSql('CREATE INDEX IDX_E21168B03A31B02B ON util_rel.virtual_page__virtual_page_resource__banner (virtual_page_id)');
        $this->addSql('CREATE INDEX IDX_E21168B0684EC833 ON util_rel.virtual_page__virtual_page_resource__banner (banner_id)');
        $this->addSql('CREATE TABLE util_rel.virtual_page__virtual_page_resource__factoid (virtual_page_id INT NOT NULL, factoid_id INT NOT NULL, PRIMARY KEY(virtual_page_id, factoid_id))');
        $this->addSql('CREATE INDEX IDX_C484F13D3A31B02B ON util_rel.virtual_page__virtual_page_resource__factoid (virtual_page_id)');
        $this->addSql('CREATE INDEX IDX_C484F13D72EC0E03 ON util_rel.virtual_page__virtual_page_resource__factoid (factoid_id)');
        $this->addSql('ALTER TABLE product_type.audio_book ADD CONSTRAINT FK_9470E1E64584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.audio_book ADD CONSTRAINT FK_9470E1E61717D737 FOREIGN KEY (reader_id) REFERENCES common.audio_book_reader (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.author__product_essence__essence ADD CONSTRAINT FK_97964C37F675F31B FOREIGN KEY (author_id) REFERENCES common.author (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.author__product_essence__essence ADD CONSTRAINT FK_97964C379FAFD5C7 FOREIGN KEY (essence_id) REFERENCES product_essence.essence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.badge ADD CONSTRAINT FK_A3E54EA54584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.bag ADD CONSTRAINT FK_10623CE4584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf ADD CONSTRAINT FK_35B30188684EC833 FOREIGN KEY (banner_id) REFERENCES virtual_page_resource.banner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf ADD CONSTRAINT FK_35B301887E2B35E3 FOREIGN KEY (banner_shelf_id) REFERENCES virtual_page_resource.banner_shelf (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_essence.book ADD CONSTRAINT FK_999CA6CE9FAFD5C7 FOREIGN KEY (essence_id) REFERENCES product_essence.essence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.bookmark ADD CONSTRAINT FK_2AA87E854584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_group.category ADD CONSTRAINT FK_BBCDFC04796A8F92 FOREIGN KEY (parent_category_id) REFERENCES product_group.category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.certificate ADD CONSTRAINT FK_5BE6A4BC4584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.cloth ADD CONSTRAINT FK_7FE46D064584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_property__color__product_type__cloth ADD CONSTRAINT FK_5F922BEC7ADA1FB5 FOREIGN KEY (color_id) REFERENCES product_property.color (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_property__color__product_type__cloth ADD CONSTRAINT FK_5F922BECE53266EE FOREIGN KEY (cloth_id) REFERENCES product_type.cloth (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.course ADD CONSTRAINT FK_D37941014584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common.creative_partner ADD CONSTRAINT FK_D2813ECFF98F144A FOREIGN KEY (logo_id) REFERENCES product_data.source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.creative_partner__product_essence__book ADD CONSTRAINT FK_8B688F0151184328 FOREIGN KEY (creative_partner_id) REFERENCES common.creative_partner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.creative_partner__product_essence__book ADD CONSTRAINT FK_8B688F0116A2B381 FOREIGN KEY (book_id) REFERENCES product_essence.book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_data.data1_c ADD CONSTRAINT FK_EB91A6544584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.e_book ADD CONSTRAINT FK_7CFE35C54584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_essence.essence ADD CONSTRAINT FK_A0A91C8612469DE2 FOREIGN KEY (category_id) REFERENCES product_group.category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_essence.essence ADD CONSTRAINT FK_A0A91C865278319C FOREIGN KEY (series_id) REFERENCES product_group.series (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_essence.essence ADD CONSTRAINT FK_A0A91C86F675F31B FOREIGN KEY (author_id) REFERENCES common.author (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__essences_with_me__same_essences ADD CONSTRAINT FK_9F1475F251FD9051 FOREIGN KEY (essences_with_me_id) REFERENCES product_essence.essence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__essences_with_me__same_essences ADD CONSTRAINT FK_9F1475F2EAD75F8 FOREIGN KEY (same_essences_id) REFERENCES product_essence.essence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__product_group__tag ADD CONSTRAINT FK_A19F1F389FAFD5C7 FOREIGN KEY (essence_id) REFERENCES product_essence.essence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__product_group__tag ADD CONSTRAINT FK_A19F1F38BAD26311 FOREIGN KEY (tag_id) REFERENCES product_group.tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE virtual_page_resource.factoid ADD CONSTRAINT FK_7D22BCE93DA5256D FOREIGN KEY (image_id) REFERENCES product_data.source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE virtual_page_resource.factoid ADD CONSTRAINT FK_7D22BCE94584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.game ADD CONSTRAINT FK_5E368B764584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.kit ADD CONSTRAINT FK_42B0D3974584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.kit_item ADD CONSTRAINT FK_12E86BE54584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.kit_item ADD CONSTRAINT FK_12E86BE53A8E60EF FOREIGN KEY (kit_id) REFERENCES product_type.kit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.notepad ADD CONSTRAINT FK_185A5F104584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.paper_book ADD CONSTRAINT FK_2D295CAD4584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.postcard ADD CONSTRAINT FK_F2F2E0C24584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.poster ADD CONSTRAINT FK_E896224A4584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common.product ADD CONSTRAINT FK_33AEC4FB9FAFD5C7 FOREIGN KEY (essence_id) REFERENCES product_essence.essence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product__product_group__promo_tag ADD CONSTRAINT FK_3158A30A4584665A FOREIGN KEY (product_id) REFERENCES common.product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product__product_group__promo_tag ADD CONSTRAINT FK_3158A30AA3577C5C FOREIGN KEY (promo_tag_id) REFERENCES product_group.promo_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product__virtual_page_resource__product_shelf ADD CONSTRAINT FK_C5F984754584665A FOREIGN KEY (product_id) REFERENCES common.product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product__virtual_page_resource__product_shelf ADD CONSTRAINT FK_C5F98475B7A29157 FOREIGN KEY (product_shelf_id) REFERENCES virtual_page_resource.product_shelf (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product__product_data__source ADD CONSTRAINT FK_752918214584665A FOREIGN KEY (product_id) REFERENCES common.product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product__product_data__source ADD CONSTRAINT FK_75291821953C1C61 FOREIGN KEY (source_id) REFERENCES product_data.source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE virtual_page_resource.product_shelf ADD CONSTRAINT FK_1031995B12469DE2 FOREIGN KEY (category_id) REFERENCES product_group.category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE virtual_page_resource.product_shelf ADD CONSTRAINT FK_1031995BBAD26311 FOREIGN KEY (tag_id) REFERENCES product_group.tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE virtual_page_resource.product_shelf ADD CONSTRAINT FK_1031995BA3577C5C FOREIGN KEY (promo_tag_id) REFERENCES product_group.promo_tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_data.promo_data ADD CONSTRAINT FK_2578E2124584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_property__size__product_type__cloth ADD CONSTRAINT FK_8FFFBB80498DA827 FOREIGN KEY (size_id) REFERENCES product_property.size (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_property__size__product_type__cloth ADD CONSTRAINT FK_8FFFBB80E53266EE FOREIGN KEY (cloth_id) REFERENCES product_type.cloth (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth.soc_network_user_data ADD CONSTRAINT FK_B7FB7888A76ED395 FOREIGN KEY (user_id) REFERENCES common.users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_data__source__product_essence__essence ADD CONSTRAINT FK_991923EE953C1C61 FOREIGN KEY (source_id) REFERENCES product_data.source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_data__source__product_essence__essence ADD CONSTRAINT FK_991923EE9FAFD5C7 FOREIGN KEY (essence_id) REFERENCES product_essence.essence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_data__source__virtual_page_resource__banner ADD CONSTRAINT FK_7E0F8BBA953C1C61 FOREIGN KEY (source_id) REFERENCES product_data.source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.product_data__source__virtual_page_resource__banner ADD CONSTRAINT FK_7E0F8BBA684EC833 FOREIGN KEY (banner_id) REFERENCES virtual_page_resource.banner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_type.sticker ADD CONSTRAINT FK_4A92606D4584665A FOREIGN KEY (product_id) REFERENCES common.product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common.virtual_page ADD CONSTRAINT FK_CC09F4E5ADFDB4D7 FOREIGN KEY (parent_virtual_page_id) REFERENCES common.virtual_page (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common.virtual_page ADD CONSTRAINT FK_CC09F4E512469DE2 FOREIGN KEY (category_id) REFERENCES product_group.category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common.virtual_page ADD CONSTRAINT FK_CC09F4E554B9D732 FOREIGN KEY (icon_id) REFERENCES product_data.source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner_shelf ADD CONSTRAINT FK_DE34ACB23A31B02B FOREIGN KEY (virtual_page_id) REFERENCES common.virtual_page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner_shelf ADD CONSTRAINT FK_DE34ACB27E2B35E3 FOREIGN KEY (banner_shelf_id) REFERENCES virtual_page_resource.banner_shelf (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__product_shelf ADD CONSTRAINT FK_9B72D8DC3A31B02B FOREIGN KEY (virtual_page_id) REFERENCES common.virtual_page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__product_shelf ADD CONSTRAINT FK_9B72D8DCB7A29157 FOREIGN KEY (product_shelf_id) REFERENCES virtual_page_resource.product_shelf (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner ADD CONSTRAINT FK_E21168B03A31B02B FOREIGN KEY (virtual_page_id) REFERENCES common.virtual_page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner ADD CONSTRAINT FK_E21168B0684EC833 FOREIGN KEY (banner_id) REFERENCES virtual_page_resource.banner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__factoid ADD CONSTRAINT FK_C484F13D3A31B02B FOREIGN KEY (virtual_page_id) REFERENCES common.virtual_page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__factoid ADD CONSTRAINT FK_C484F13D72EC0E03 FOREIGN KEY (factoid_id) REFERENCES virtual_page_resource.factoid (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_type.audio_book DROP CONSTRAINT FK_9470E1E61717D737');
        $this->addSql('ALTER TABLE util_rel.author__product_essence__essence DROP CONSTRAINT FK_97964C37F675F31B');
        $this->addSql('ALTER TABLE product_essence.essence DROP CONSTRAINT FK_A0A91C86F675F31B');
        $this->addSql('ALTER TABLE util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf DROP CONSTRAINT FK_35B30188684EC833');
        $this->addSql('ALTER TABLE util_rel.product_data__source__virtual_page_resource__banner DROP CONSTRAINT FK_7E0F8BBA684EC833');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner DROP CONSTRAINT FK_E21168B0684EC833');
        $this->addSql('ALTER TABLE util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf DROP CONSTRAINT FK_35B301887E2B35E3');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner_shelf DROP CONSTRAINT FK_DE34ACB27E2B35E3');
        $this->addSql('ALTER TABLE util_rel.creative_partner__product_essence__book DROP CONSTRAINT FK_8B688F0116A2B381');
        $this->addSql('ALTER TABLE product_group.category DROP CONSTRAINT FK_BBCDFC04796A8F92');
        $this->addSql('ALTER TABLE product_essence.essence DROP CONSTRAINT FK_A0A91C8612469DE2');
        $this->addSql('ALTER TABLE virtual_page_resource.product_shelf DROP CONSTRAINT FK_1031995B12469DE2');
        $this->addSql('ALTER TABLE common.virtual_page DROP CONSTRAINT FK_CC09F4E512469DE2');
        $this->addSql('ALTER TABLE util_rel.product_property__color__product_type__cloth DROP CONSTRAINT FK_5F922BECE53266EE');
        $this->addSql('ALTER TABLE util_rel.product_property__size__product_type__cloth DROP CONSTRAINT FK_8FFFBB80E53266EE');
        $this->addSql('ALTER TABLE util_rel.product_property__color__product_type__cloth DROP CONSTRAINT FK_5F922BEC7ADA1FB5');
        $this->addSql('ALTER TABLE util_rel.creative_partner__product_essence__book DROP CONSTRAINT FK_8B688F0151184328');
        $this->addSql('ALTER TABLE util_rel.author__product_essence__essence DROP CONSTRAINT FK_97964C379FAFD5C7');
        $this->addSql('ALTER TABLE product_essence.book DROP CONSTRAINT FK_999CA6CE9FAFD5C7');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__essences_with_me__same_essences DROP CONSTRAINT FK_9F1475F251FD9051');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__essences_with_me__same_essences DROP CONSTRAINT FK_9F1475F2EAD75F8');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__product_group__tag DROP CONSTRAINT FK_A19F1F389FAFD5C7');
        $this->addSql('ALTER TABLE common.product DROP CONSTRAINT FK_33AEC4FB9FAFD5C7');
        $this->addSql('ALTER TABLE util_rel.product_data__source__product_essence__essence DROP CONSTRAINT FK_991923EE9FAFD5C7');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__factoid DROP CONSTRAINT FK_C484F13D72EC0E03');
        $this->addSql('ALTER TABLE product_type.kit_item DROP CONSTRAINT FK_12E86BE53A8E60EF');
        $this->addSql('ALTER TABLE product_type.audio_book DROP CONSTRAINT FK_9470E1E64584665A');
        $this->addSql('ALTER TABLE product_type.badge DROP CONSTRAINT FK_A3E54EA54584665A');
        $this->addSql('ALTER TABLE product_type.bag DROP CONSTRAINT FK_10623CE4584665A');
        $this->addSql('ALTER TABLE product_type.bookmark DROP CONSTRAINT FK_2AA87E854584665A');
        $this->addSql('ALTER TABLE product_type.certificate DROP CONSTRAINT FK_5BE6A4BC4584665A');
        $this->addSql('ALTER TABLE product_type.cloth DROP CONSTRAINT FK_7FE46D064584665A');
        $this->addSql('ALTER TABLE product_type.course DROP CONSTRAINT FK_D37941014584665A');
        $this->addSql('ALTER TABLE product_data.data1_c DROP CONSTRAINT FK_EB91A6544584665A');
        $this->addSql('ALTER TABLE product_type.e_book DROP CONSTRAINT FK_7CFE35C54584665A');
        $this->addSql('ALTER TABLE virtual_page_resource.factoid DROP CONSTRAINT FK_7D22BCE94584665A');
        $this->addSql('ALTER TABLE product_type.game DROP CONSTRAINT FK_5E368B764584665A');
        $this->addSql('ALTER TABLE product_type.kit DROP CONSTRAINT FK_42B0D3974584665A');
        $this->addSql('ALTER TABLE product_type.kit_item DROP CONSTRAINT FK_12E86BE54584665A');
        $this->addSql('ALTER TABLE product_type.notepad DROP CONSTRAINT FK_185A5F104584665A');
        $this->addSql('ALTER TABLE product_type.paper_book DROP CONSTRAINT FK_2D295CAD4584665A');
        $this->addSql('ALTER TABLE product_type.postcard DROP CONSTRAINT FK_F2F2E0C24584665A');
        $this->addSql('ALTER TABLE product_type.poster DROP CONSTRAINT FK_E896224A4584665A');
        $this->addSql('ALTER TABLE util_rel.product__product_group__promo_tag DROP CONSTRAINT FK_3158A30A4584665A');
        $this->addSql('ALTER TABLE util_rel.product__virtual_page_resource__product_shelf DROP CONSTRAINT FK_C5F984754584665A');
        $this->addSql('ALTER TABLE util_rel.product__product_data__source DROP CONSTRAINT FK_752918214584665A');
        $this->addSql('ALTER TABLE product_data.promo_data DROP CONSTRAINT FK_2578E2124584665A');
        $this->addSql('ALTER TABLE product_type.sticker DROP CONSTRAINT FK_4A92606D4584665A');
        $this->addSql('ALTER TABLE util_rel.product__virtual_page_resource__product_shelf DROP CONSTRAINT FK_C5F98475B7A29157');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__product_shelf DROP CONSTRAINT FK_9B72D8DCB7A29157');
        $this->addSql('ALTER TABLE util_rel.product__product_group__promo_tag DROP CONSTRAINT FK_3158A30AA3577C5C');
        $this->addSql('ALTER TABLE virtual_page_resource.product_shelf DROP CONSTRAINT FK_1031995BA3577C5C');
        $this->addSql('ALTER TABLE product_essence.essence DROP CONSTRAINT FK_A0A91C865278319C');
        $this->addSql('ALTER TABLE util_rel.product_property__size__product_type__cloth DROP CONSTRAINT FK_8FFFBB80498DA827');
        $this->addSql('ALTER TABLE common.creative_partner DROP CONSTRAINT FK_D2813ECFF98F144A');
        $this->addSql('ALTER TABLE virtual_page_resource.factoid DROP CONSTRAINT FK_7D22BCE93DA5256D');
        $this->addSql('ALTER TABLE util_rel.product__product_data__source DROP CONSTRAINT FK_75291821953C1C61');
        $this->addSql('ALTER TABLE util_rel.product_data__source__product_essence__essence DROP CONSTRAINT FK_991923EE953C1C61');
        $this->addSql('ALTER TABLE util_rel.product_data__source__virtual_page_resource__banner DROP CONSTRAINT FK_7E0F8BBA953C1C61');
        $this->addSql('ALTER TABLE common.virtual_page DROP CONSTRAINT FK_CC09F4E554B9D732');
        $this->addSql('ALTER TABLE util_rel.product_essence__essence__product_group__tag DROP CONSTRAINT FK_A19F1F38BAD26311');
        $this->addSql('ALTER TABLE virtual_page_resource.product_shelf DROP CONSTRAINT FK_1031995BBAD26311');
        $this->addSql('ALTER TABLE common.virtual_page DROP CONSTRAINT FK_CC09F4E5ADFDB4D7');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner_shelf DROP CONSTRAINT FK_DE34ACB23A31B02B');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__product_shelf DROP CONSTRAINT FK_9B72D8DC3A31B02B');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__banner DROP CONSTRAINT FK_E21168B03A31B02B');
        $this->addSql('ALTER TABLE util_rel.virtual_page__virtual_page_resource__factoid DROP CONSTRAINT FK_C484F13D3A31B02B');
        $this->addSql('DROP TABLE product_type.audio_book');
        $this->addSql('DROP TABLE common.audio_book_reader');
        $this->addSql('DROP TABLE common.author');
        $this->addSql('DROP TABLE util_rel.author__product_essence__essence');
        $this->addSql('DROP TABLE product_type.badge');
        $this->addSql('DROP TABLE product_type.bag');
        $this->addSql('DROP TABLE virtual_page_resource.banner');
        $this->addSql('DROP TABLE util_rel.virtual_page_resource__banner__virtual_page_resource__banner_shelf');
        $this->addSql('DROP TABLE virtual_page_resource.banner_shelf');
        $this->addSql('DROP TABLE product_essence.book');
        $this->addSql('DROP TABLE product_type.bookmark');
        $this->addSql('DROP TABLE product_group.category');
        $this->addSql('DROP TABLE product_type.certificate');
        $this->addSql('DROP TABLE product_type.cloth');
        $this->addSql('DROP TABLE product_property.color');
        $this->addSql('DROP TABLE util_rel.product_property__color__product_type__cloth');
        $this->addSql('DROP TABLE product_type.course');
        $this->addSql('DROP TABLE common.creative_partner');
        $this->addSql('DROP TABLE util_rel.creative_partner__product_essence__book');
        $this->addSql('DROP TABLE product_data.data1_c');
        $this->addSql('DROP TABLE product_type.e_book');
        $this->addSql('DROP TABLE product_essence.essence');
        $this->addSql('DROP TABLE util_rel.product_essence__essence__essences_with_me__same_essences');
        $this->addSql('DROP TABLE util_rel.product_essence__essence__product_group__tag');
        $this->addSql('DROP TABLE virtual_page_resource.factoid');
        $this->addSql('DROP TABLE virtual_page_resource.free_block');
        $this->addSql('DROP TABLE product_type.game');
        $this->addSql('DROP TABLE product_type.kit');
        $this->addSql('DROP TABLE product_type.kit_item');
        $this->addSql('DROP TABLE product_type.notepad');
        $this->addSql('DROP TABLE product_type.paper_book');
        $this->addSql('DROP TABLE product_type.postcard');
        $this->addSql('DROP TABLE product_type.poster');
        $this->addSql('DROP TABLE common.product');
        $this->addSql('DROP TABLE util_rel.product__product_group__promo_tag');
        $this->addSql('DROP TABLE util_rel.product__virtual_page_resource__product_shelf');
        $this->addSql('DROP TABLE util_rel.product__product_data__source');
        $this->addSql('DROP TABLE virtual_page_resource.product_shelf');
        $this->addSql('DROP TABLE product_data.promo_data');
        $this->addSql('DROP TABLE product_group.promo_tag');
        $this->addSql('DROP TABLE product_group.series');
        $this->addSql('DROP TABLE product_property.size');
        $this->addSql('DROP TABLE util_rel.product_property__size__product_type__cloth');
        $this->addSql('DROP TABLE auth.soc_network_user_data');
        $this->addSql('DROP TABLE product_data.source');
        $this->addSql('DROP TABLE util_rel.product_data__source__product_essence__essence');
        $this->addSql('DROP TABLE util_rel.product_data__source__virtual_page_resource__banner');
        $this->addSql('DROP TABLE product_type.sticker');
        $this->addSql('DROP TABLE product_group.tag');
        $this->addSql('DROP TABLE common.virtual_page');
        $this->addSql('DROP TABLE util_rel.virtual_page__virtual_page_resource__banner_shelf');
        $this->addSql('DROP TABLE util_rel.virtual_page__virtual_page_resource__product_shelf');
        $this->addSql('DROP TABLE util_rel.virtual_page__virtual_page_resource__banner');
        $this->addSql('DROP TABLE util_rel.virtual_page__virtual_page_resource__factoid');
    }
}
